analyzer:
  errors:
    # Disable everything
    missing_return: ignore
    unused_import: ignore
    unused_local_variable: ignore
    dead_code: ignore
    todo: ignore
    always_declare_return_types: ignore
    avoid_print: ignore
    non_constant_identifier_names: ignore
    prefer_const_constructors: ignore
    unnecessary_this: ignore
    unused_field: ignore
    parameter_assignments: ignore
    avoid_types_on_closure_parameters: ignore
    prefer_final_fields: ignore
    avoid_init_to_null: ignore
    unnecessary_new: ignore
    constant_identifier_names: ignore
    prefer_single_quotes: ignore
    annotate_overrides: ignore
    argument_type_not_assignable: ignore
    missing_required_argument: ignore
    assignment_to_final: ignore
    assignment_to_const: ignore
    file_names: ignore
    sort_pub_dependencies: ignore
    non_bool_condition: ignore
    return_of_invalid_type:  ignore
    depend_on_referenced_packages: ignore
    camel_case_types: ignore
    empty_constructor_bodies: ignore
    avoid_empty_else: ignore
    use_key_in_widget_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_declarations: ignore
    unnecessary_const: ignore
    unused_element: ignore
    avoid_web_libraries_in_flutter: ignore
    no_logic_in_create_state: ignore

linter:
  rules: []
